[profile.default]
src    = "contracts/src"
out    = "contracts/out"
libs   = ["contracts/lib"]
test   = "contracts/test"
script = "contracts/scripts"
remappings = [
    "@openzeppelin/contracts/=contracts/lib/openzeppelin-contracts/contracts/",
    "forge-std/=contracts/lib/forge-std/src/",
]
fs_permissions = [{ access = "write", path = "./deployments.json" }]
